# DAY 10

### MACHINE LEARNING

READ DATA FROM WEBSCRAPING USING INSTANT DATA SCRAPER EXTENSION

In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv('D:/REGEX/DAY_10/hotel.csv')
df.head()

NAME    Restaurant_details  \
0  The DeIicious Yard // family restaurants in ja...       ·  · Restaurant   
1                      Mr Tandoor Hotel & Restaurant       ·  · Restaurant   
2  Dorothea Cafe | Jaipur | Restaurant | Global C...          · Restaurant   
3                                     Tandoori Grill     ·  · North Indian   
4                      The resort hotel & restaurant  ·  · Family-friendly   

   yi40Hd  RDApEe      rate  \
0     4.7   (693)  ₹200–600   
1     5.0    (18)  ₹400–600   
2     4.7  (1.1K)       NaN   
3     4.8    (86)  ₹200–400   
4     4.7    (46)  ₹200–400   

                                             address  \
0  3, Panchawati Colony, Plot No.- 2, in front of...   
1             Commercial Complex, C-50, near Genpact   
2                                       Plot no- 10A   
3     GROUND FLOOR, Shopping Centre, Rana Sanga Marg   
4                                14H - 222 khatipura   

                                            map_link      type  \
0  data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYi...  Veg-only   
1  https://lh3.googleusercontent.com/gps-cs-s/AC9...       NaN   
2  https://lh3.googleusercontent.com/p/AF1QipMTrN...       NaN   
3  https://lh3.googleusercontent.com/p/AF1QipMC9v...       NaN   
4  https://lh3.googleusercontent.com/gps-cs-s/AC9...       NaN   

                                              images   BI0Dve if66xd  \
0  https://lh3.googleusercontent.com/p/AF1QipOE00...      NaN    NaN   
1                                                NaN  Dine-in      ·   
2                                                NaN  Dine-in      ·   
3                                                NaN  Dine-in      ·   
4                                                NaN  Dine-in      ·   

        BI0Dve 2             BI0Dve 3  
0            NaN                  NaN  
1  Drive-through  No-contact delivery  
2       Takeaway                  NaN  
3  Drive-through  No-contact delivery  
4  Drive-through                  NaN

In [4]:
df.rename(columns={'yi40Hd': 'Rating'}, inplace=True)

In [5]:
df.head()

NAME    Restaurant_details  \
0  The DeIicious Yard // family restaurants in ja...       ·  · Restaurant   
1                      Mr Tandoor Hotel & Restaurant       ·  · Restaurant   
2  Dorothea Cafe | Jaipur | Restaurant | Global C...          · Restaurant   
3                                     Tandoori Grill     ·  · North Indian   
4                      The resort hotel & restaurant  ·  · Family-friendly   

   Rating  RDApEe      rate  \
0     4.7   (693)  ₹200–600   
1     5.0    (18)  ₹400–600   
2     4.7  (1.1K)       NaN   
3     4.8    (86)  ₹200–400   
4     4.7    (46)  ₹200–400   

                                             address  \
0  3, Panchawati Colony, Plot No.- 2, in front of...   
1             Commercial Complex, C-50, near Genpact   
2                                       Plot no- 10A   
3     GROUND FLOOR, Shopping Centre, Rana Sanga Marg   
4                                14H - 222 khatipura   

                                            map_link      type  \
0  data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYi...  Veg-only   
1  https://lh3.googleusercontent.com/gps-cs-s/AC9...       NaN   
2  https://lh3.googleusercontent.com/p/AF1QipMTrN...       NaN   
3  https://lh3.googleusercontent.com/p/AF1QipMC9v...       NaN   
4  https://lh3.googleusercontent.com/gps-cs-s/AC9...       NaN   

                                              images   BI0Dve if66xd  \
0  https://lh3.googleusercontent.com/p/AF1QipOE00...      NaN    NaN   
1                                                NaN  Dine-in      ·   
2                                                NaN  Dine-in      ·   
3                                                NaN  Dine-in      ·   
4                                                NaN  Dine-in      ·   

        BI0Dve 2             BI0Dve 3  
0            NaN                  NaN  
1  Drive-through  No-contact delivery  
2       Takeaway                  NaN  
3  Drive-through  No-contact delivery  
4  Drive-through                  NaN

In [6]:
df.rename(columns={'RDApEe': 'Review'}, inplace=True)

In [7]:
df.head()

NAME    Restaurant_details  \
0  The DeIicious Yard // family restaurants in ja...       ·  · Restaurant   
1                      Mr Tandoor Hotel & Restaurant       ·  · Restaurant   
2  Dorothea Cafe | Jaipur | Restaurant | Global C...          · Restaurant   
3                                     Tandoori Grill     ·  · North Indian   
4                      The resort hotel & restaurant  ·  · Family-friendly   

   Rating  Review      rate  \
0     4.7   (693)  ₹200–600   
1     5.0    (18)  ₹400–600   
2     4.7  (1.1K)       NaN   
3     4.8    (86)  ₹200–400   
4     4.7    (46)  ₹200–400   

                                             address  \
0  3, Panchawati Colony, Plot No.- 2, in front of...   
1             Commercial Complex, C-50, near Genpact   
2                                       Plot no- 10A   
3     GROUND FLOOR, Shopping Centre, Rana Sanga Marg   
4                                14H - 222 khatipura   

                                            map_link      type  \
0  data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYi...  Veg-only   
1  https://lh3.googleusercontent.com/gps-cs-s/AC9...       NaN   
2  https://lh3.googleusercontent.com/p/AF1QipMTrN...       NaN   
3  https://lh3.googleusercontent.com/p/AF1QipMC9v...       NaN   
4  https://lh3.googleusercontent.com/gps-cs-s/AC9...       NaN   

                                              images   BI0Dve if66xd  \
0  https://lh3.googleusercontent.com/p/AF1QipOE00...      NaN    NaN   
1                                                NaN  Dine-in      ·   
2                                                NaN  Dine-in      ·   
3                                                NaN  Dine-in      ·   
4                                                NaN  Dine-in      ·   

        BI0Dve 2             BI0Dve 3  
0            NaN                  NaN  
1  Drive-through  No-contact delivery  
2       Takeaway                  NaN  
3  Drive-through  No-contact delivery  
4  Drive-through                  NaN

In [8]:
df.rename(columns={'BI0Dve': 'Booking_System'}, inplace=True)

In [9]:
df=pd.read_csv('D:/REGEX/DAY_10/placement.csv')
df.head()

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [10]:
df.shape

(100, 3)

DATA DIVIDATION 

SPLIT ON DEPENDENT AND INDEPENDENT 

In [ ]:
x=df.drop(columns='placed') # input data
y=df['placed'] # target data


In [14]:
print(x)

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]


In [15]:
print(y)

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64


TRAINING AND TESTING DATA SPLIT

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

SEED SCRIPTING IN NUMPY

In [35]:
a= np.random.randint(1, 100, size=(1, 2,2))
print(a)

[[[51 76]
  [90 66]]]


In [29]:
np.random.seed(43)
a= np.random.randint(1, 100, size=(1, 3,3))
print(a)

[[[69 65 50]
  [22 59 17]
  [52 18 60]]]


In [33]:
print("TOTAL DATA SHAPE :", df.shape)
print("INPUT DATA SHAPE :", x.shape)
print("X_TRAIN DATA SHAPE :", x_train.shape)
print("X_TEST DATA SHAPE :", x_test.shape)
print("--------------------------------------")
print("TARGET DATA SHAPE :", y.shape)
print("Y_TRAIN DATA SHAPE :", y_train.shape)
print("Y_TEST DATA SHAPE :", y_test.shape)

TOTAL DATA SHAPE : (100, 3)
INPUT DATA SHAPE : (100, 2)
X_TRAIN DATA SHAPE : (80, 2)
X_TEST DATA SHAPE : (20, 2)
--------------------------------------
TARGET DATA SHAPE : (100,)
Y_TRAIN DATA SHAPE : (80,)
Y_TEST DATA SHAPE : (20,)


In [ ]:
# df(100,3)=x(100,2)+ y(100,1)
# x(100,2)=x_train(80,2)+ x_test(20,2)
# y(100,1)=y_train(80,1)+ y_test(20,1)