# DATA ANALYTICS

DATA ANALYTICS : DATA ANALYSES

### DATA IN FORM OF :-
1. JSON , DICTIONARY{}
2. DATABASE
3. CSV FILES
4. PEN PAPER

### DATA TRANSFORMATION :-
1. DATA CLEANING
2. DATA STORE
2. DATA TRANSFORMATION
3. DATA ANALYSIS
4. DATA VISUALIZATION


### FLOW OF DATA ANALYTICS :-

=> PROBLEM SOLVING
=> DOCUMENTATION CREATION
=> DATA CLEANING
=> DATA TRANSFORMATION
=> DATA ANALYSIS
=> MACHING LEARNING
=> DATA VISUALIZATION

# DATA PROCESSING AND DATA CLEANING PACKAGE

## NUMPY

=> INBUILT PACKAGE FOR DATA PROCESSING 
=> NUMERICAL PYTHON => USED TO PERFORM MATHEMATICAL OPERATION

In [2]:
# NUMPY 
# NUMPY => ARRAY
# CONTINUOUS MEMORY LOCATION MEMORY ADDRESS
# ALL WHILE OF SAME DATATYPE
# INT THEN ALL INT

In [4]:
# NUMPY => IT IS USED TO SPEED UP THE MATHEMATICAL TASK ON MY DATA ( LIKE ADDITION ,SUBSTRACTION,...)
# pip install numpy

In [1]:
import numpy as np
data =[10,20,30,40]
arr=np.array(data)
print(f"TYPE OF DATA => {type (data)}\nTYPE OF ARR => {type(arr)}")

TYPE OF DATA => <class 'list'>
TYPE OF ARR => <class 'numpy.ndarray'>


### DTYPE => SHOW THE DATA TYPE

In [10]:
arr=np.array(data,dtype='complex')
print(f"TYPE OF DATA => {type (data)}\nTYPE OF ARR => {type(arr)}\narr => {arr}")

TYPE OF DATA => <class 'list'>
TYPE OF ARR => <class 'numpy.ndarray'>
arr => [10.+0.j 20.+0.j 30.+0.j 40.+0.j]


In [11]:
arr=np.array(data,dtype='float')
print(f"TYPE OF DATA => {type (data)}\nTYPE OF ARR => {type(arr)}\narr => {arr}")

TYPE OF DATA => <class 'list'>
TYPE OF ARR => <class 'numpy.ndarray'>
arr => [10. 20. 30. 40.]


### ACCESSING DATA IN NUMPY

In [ ]:
# [[4,5][45,56]]
# => TO ACCESS 4 => [1][0]


### ARRAY SHAPE

In [14]:
data =[2,3,4,5]
arr=np.array(data)
print(arr.shape)

(4,)


### 2D ARRAY

In [ ]:
data =[[2,3,4,5],[34,43,66,87]]
arr=np.array(data)
print(arr.shape)

(2, 4)


### ASTYPE => DATA TYPE CHANGE

In [26]:
import numpy as np
data =[[2,3,4,5],[34,43,66,87]]
arr=np.array(data)
print(arr.shape)
print(type(arr))
np=arr.astype(np.float32)
print(type(arr))
print(np)

(2, 4)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[ 2.  3.  4.  5.]
 [34. 43. 66. 87.]]


In [34]:
import numpy as np
data =[[2,3,4,5],[34,43,66,87]]
arr=np.array(data)
arr=np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [35]:
import numpy as np
data =[[2,3,4,5],[34,43,66,87]]
arr=np.array(data)
arr=np.shape
print(arr)

<function shape at 0x00000241F3134860>


### ZERO FUNCTION IN NUMPY

In [28]:
import numpy as np
arr1=np.zeros(4)
print(arr1)

[0. 0. 0. 0.]


In [47]:
import numpy as np
arr3=np.zeros(4)
arr3=arr3.reshape(2,2)
print(arr3)

[[0. 0.]
 [0. 0.]]


In [30]:
import numpy as np
arr2=np.ones(4)
print(arr2)

[1. 1. 1. 1.]


In [53]:
import numpy as np
arr=np.full(5,4,float)
print(arr)

[4. 4. 4. 4. 4.]


### EMPTY IN NUMPY

In [54]:
import numpy as np
arr=np.empty(5)
print(arr)

[4. 4. 4. 4. 4.]


### CHEACK WHICH IS FAST 

#### NUMPY VS ARRAY

In [ ]:
# [10,20]*2
for in range (4):
    

In [61]:
a=list(range(10000))
arr=np.arange(10000)



### CHECK USING TIME

In [67]:
%timeit for _ in range (1000): a2=a*2
print(type(a))

46.7 ms ± 2.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
<class 'list'>


In [68]:
%timeit for _ in range (1000): arr2=arr*2
print(type(arr2))

6.35 ms ± 346 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
<class 'numpy.ndarray'>


### ADD IN DATA IN NUMPY

In [64]:
arr1=np.array(4)
arr1+8

np.int64(12)

In [94]:
import numpy as np
arr=np.arange(16).reshape(4,4)
print(arr)
print("print 1 and 2",arr[1:2])
print ("print 9 and 10",arr[2,1:3])
print ("print [0,4][2,6] and 10",arr[0:2,0:3:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
print 1 and 2 [[4 5 6 7]]
print 9 and 10 [ 9 10]
print [0,4][2,6] and 10 [[0 2]
 [4 6]]


### SCALER IN NUMPY

A=5

In [95]:
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# Functions
print("Add 3:", np.add(scalar, 3))
print("Multiply by 2:", np.multiply(scalar, 2))
print("Square root:", np.sqrt(scalar))
print("Power (scalar^2):", np.power(scalar, 2))

Scalar: 5
Add 3: 8
Multiply by 2: 10
Square root: 2.23606797749979
Power (scalar^2): 25


### VECTOR IN NUMPY

1 D ARRAY

In [96]:
vector = np.array([1, 2, 3, 4])
print("Vector:", vector)
print("Sum:", np.sum(vector))
print("Mean:", np.mean(vector))
print("Standard Deviation:", np.std(vector))
print("Max:", np.max(vector))
print("Min:", np.min(vector))
print("Sorted:", np.sort(vector))
print("Cumulative Sum:", np.cumsum(vector))
print("Square of each element:", np.square(vector))
print("Sine of each element:", np.sin(vector))
print("Reshape to column vector:\n", vector.reshape(-1, 1))


Vector: [1 2 3 4]
Sum: 10
Mean: 2.5
Standard Deviation: 1.118033988749895
Max: 4
Min: 1
Sorted: [1 2 3 4]
Cumulative Sum: [ 1  3  6 10]
Square of each element: [ 1  4  9 16]
Sine of each element: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Reshape to column vector:
 [[1]
 [2]
 [3]
 [4]]


### ROW VECTOR

1 ROW MULTIPLY COLUMN => (1 X n)

In [99]:
import numpy as np
row_vector = np.array([[1, 2, 3]])
print("Row Vector:", row_vector)
print("SHAPE => ",row_vector.shape)  # Output: (1, 3)

Row Vector: [[1 2 3]]
SHAPE =>  (1, 3)


### COLUMN VECTOR

1 COLUMN MULTIPLE ROWS => (n X 1)

In [101]:
import numpy as np
column_vector = np.array([[1], [2], [3]])
print("Column Vector:\n", column_vector)
print("SHAPE => ",column_vector.shape) 


Column Vector:
 [[1]
 [2]
 [3]]
SHAPE =>  (3, 1)


### CONVERT ROW TO COLUMN & COLUMN TO ROW

In [106]:
# Row to Column
col = row_vector.T

# Column to Row
row = column_vector.T


In [103]:
print(col)
print(row)

[[1]
 [2]
 [3]]
[[1 2 3]]


### MATRIX

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)
# Basic Stats
print("Shape:", matrix.shape)
print("Transpose:\n", matrix.T)
print("Sum along columns:", np.sum(matrix, axis=0))
print("Sum along rows:", np.sum(matrix, axis=1))

# Matrix Multiplication
mat2 = np.array([[5, 6], [7, 8]])
print("Second Matrix:\n", mat2)
print("Matrix Dot Product:\n", np.dot(matrix, mat2))

# Inverse (only for square matrix)
print("Inverse:\n", np.linalg.inv(matrix))

# Determinant
print("Determinant:", np.linalg.det(matrix))

# Eigenvalues and Eigenvectors
eigvals, eigvecs = np.linalg.eig(matrix)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

# Flatten
print("Flattened Matrix:", matrix.flatten())


Matrix:
 [[1 2]
 [3 4]]
Shape: (2, 2)
Transpose:
 [[1 3]
 [2 4]]
Sum along columns: [4 6]
Sum along rows: [3 7]
Second Matrix:
 [[5 6]
 [7 8]]
Matrix Dot Product:
 [[19 22]
 [43 50]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Flattened Matrix: [1 2 3 4]


In [104]:
# HOMEWORK => TRANPOSE, RESHAPE, MOVEAXIS,CREATING 3D MATRIX

In [110]:
matrix = np.array([[1, 2,4][3,4,5][5,6,6], [3, 6,4][4,6,5][6,7],[2,7,4][5,9,4][7,8,9]])
print("Matrix:\n", matrix)


<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\Dell\AppData\Local\Temp\ipykernel_31116\2354105841.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  matrix = np.array([[1, 2,4][3,4,5][5,6,6], [3, 6,4][4,6,5][6,7],[2,7,4][5,9,4][7,8,9]])
C:\Users\Dell\AppData\Local\Temp\ipykernel_31116\2354105841.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps yo

TypeError: list indices must be integers or slices, not tuple

# EDA

EXPLORATORY DATA ANALYSIS

PANDAS, MATPLOTLIB