# DAY 13

## FUNCTION TRANSFORMER

In [2]:
#FUNCTION TRANSFPORMER ----> IF YOU WANT TO APPLY ANYB OPERATION (PRE-DEFINED,CUSTOM) THEN WE CAN USE FUNCTION TRANSFORMER
 
# FUNCTION TRANSFORMER (<LOGIC_NAME>.TRANSFORMER(<DATA>))

In [3]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

CREATE A DATASET

In [5]:
X=np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


#### DEFINE TRANSFORMER FUNCTION

In [7]:
log_transformer =FunctionTransformer(np.sqrt)
print(log_transformer)

FunctionTransformer(func=<ufunc 'sqrt'>)


#### APPLY TRANSFORMER IN THE DATA SET

In [8]:
X_transformed = log_transformer.transform(X)

In [9]:
print(X_transformed)

[[1.         1.41421356]
 [1.73205081 2.        ]]


### CUSTOM FEATURE ENGINEERING

In [10]:
X=np.array([[1,2],[3,4]])

#### CREATE A FUNCTION

In [11]:
def squ(X):
    return np.hstack((X,X**2))

In [12]:
custom_transformer=FunctionTransformer(squ)

In [14]:
X_transformed=custom_transformer.transform(X)
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


#### SCALING AND NORMALIZATION

In [15]:
# => SCALING ----> MAKING DATA IN SATURATED FORMAT

##### CREATE A DATASET

In [17]:
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


#### DEFINE A CUSTOM SCALING FUNCTION

In [18]:
def my_scaling(X):
    return X/np.max(X)

#### APPLY FUNCTION TRANSFORMER TO THE FUNCTION

In [19]:
custom_transformer = FunctionTransformer(my_scaling)

#### APPLY TRANSFORMER IN INPUT DATA

In [20]:
X_transformed = custom_transformer.transform(X)

#### VIEW THE DATA AFTER APPLING TRANSFORMER

In [21]:
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


## COLUMN TRANSFORMER

CONTAINER ----> STEPS TO PROCESS ---->

TRANSFORMER ----> ('CONSTANT','OPERATION_NAME','COLUMN_NAME')

DF ----> 1-1 SINGLE COLUMN

CATEGORICAL ----> MISSING DATA FILL --->  ENCODE

NUMERICAL ----> MISSING DATA FILL   ----> NORMAL DISTRIBUTION

1-1 COLUMN ---> SHAPE ----> ALL COLUMN SHAPE CONCATENATE ---> OUTPUT

COLUMN TRANSFORMER ---> ALL COLUMN SHAPE CONCATENATE ---> OUTPUT ----> SAME

In [23]:
import numpy as np
import pandas as pd

In [26]:
df=pd.read_csv('D:\REGEX\DAY_12\covid_toy.csv')
df.head(5)

<>:1: SyntaxWarning: invalid escape sequence '\R'
<>:1: SyntaxWarning: invalid escape sequence '\R'
C:\Users\Dell\AppData\Local\Temp\ipykernel_29416\3827455808.py:1: SyntaxWarning: invalid escape sequence '\R'
  df=pd.read_csv('D:\REGEX\DAY_12\covid_toy.csv')


age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [28]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [30]:
from sklearn.model_selection import train_test_split
x=df.drop(columns=['has_covid'])
y=df['has_covid']
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42) 

In [31]:
X_test.head()

age  gender  fever   cough       city
83   17  Female  104.0    Mild    Kolkata
53   83    Male   98.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

### MANUALLY TYPED OUTPUT

#### SIMPLEIMPUTER ----> MISSING DATA FILLING

In [ ]:
si=SimpleImputer(strategy='mean')
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.transform(X_test[['fever']]) # also test the data
X_train_fever.shape

(80, 1)

#### ORDINAL ENCODING  -----> COUGH

In [33]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

#### ONE HOT ENCODING ----> GENDER, CITY

In [34]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_train_gender_city.shape

(80, 4)

#### EXTRACTING AGE

In [37]:
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_train_age.shape

(80, 1)

#### CONCATENATE ALL THE TRAIN COLUMNS

In [38]:
X_train_transformed=np.concatenate((X_train_fever,X_train_cough,X_train_gender_city,X_train_age),axis=1)
# axis =1 -----> column wise concatenation

In [39]:
X_train_transformed.shape

(80, 7)

## USING COLUMN TRANSFORMER

In [43]:
from sklearn.compose import ColumnTransformer

In [47]:
transformer= ColumnTransformer(transformers=[ ('tnf1',SimpleImputer(),['fever']), # in a 'fever' column we are applying SimpleImputer we fill the mising values with mean,median,most_frequent
                                              ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']), # in a 'cough' column we are applying OrdinalEncoder  we encode our data
                                              ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])], # in gender and city columns we are applying OneHotEncoder, we drop the first column to avoid dummy variable trap
                                            remainder='passthrough') # aremainder => passthrough => it means rest all the columns reamin same as it is.

In [48]:
a=transformer.fit_transform(X_train)
print(a.shape)

(80, 7)
